### ISSUE TITLE
UDPReceiver

### ISSUE THREAD

**Issue by air798** [is-centre/udp-ue4-plugin-win64#1]
I'm sorry to disturb you. I want to know how to write in the receiver blueprint. Can you guide me? Be deeply grateful!

**Comment by extall** [comment]
The procedure doesn't really differ from the UDPSender implementation. Create new Actor BP, use UDPReceiver as the parent class and proceed from there. Obviously, you need to initialize the socket prior to using the Actor instance, so in the Level BP do that by using a reference to the Actor BP instance.

**Comment by extall** [comment]
Added a video showing how to use UDPReceiver.
