### ISSUE TITLE
"Break UDP Data" List is not updated?

### ISSUE THREAD

**Issue by NeumeisterGit** [is-centre/udp-ue4-plugin-win64#10]
![image](https://user-images.githubusercontent.com/72918486/203281021-5553ade4-507c-41f7-8634-2abea5756ddc.png)
Hello, I have a question! I need my own data types... I want to receive 14 pieces of 8byte data types, so I made 14 double in the header file. Now I want to use them later in my project, but when I want to "Break UDP Data" in Blueprint of my Receiver, there are still only the old "floats" and "unit" inside... How can I fix this?

This is my code from "UDPData.h":

#pragma once

#include "Serialization/Archive.h"
#include "UDPData.generated.h"

USTRUCT(BlueprintType)
struct FUDPData {
	GENERATED_USTRUCT_BODY()
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double platform_x = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double platform_y = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double platform_z = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double platform_roll = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double platform_pitch = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double platform_yaw = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_1a = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_1b = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_1c = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_1d = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_2a = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_2b = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_2c = 0.0d;
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		double drive_2d = 0.0d;
	FUDPData() {
	}
};

FORCEINLINE FArchive& operator<<(FArchive &Ar, FUDPData &Structure)
{
	Ar << Structure.platform_x;
	Ar << Structure.platform_y;
	Ar << Structure.platform_z;
	Ar << Structure.platform_roll;
	Ar << Structure.platform_pitch;
	Ar << Structure.platform_yaw;
	Ar << Structure.drive_1a;
	Ar << Structure.drive_1b;
	Ar << Structure.drive_1c;
	Ar << Structure.drive_1d;
	Ar << Structure.drive_2a;
	Ar << Structure.drive_2b;
	Ar << Structure.drive_2c;
	Ar << Structure.drive_2d;
	return Ar;
}

And in the picture you see what happens, when I want to "Break UDP Data"

**Comment by extall** [comment]
@saleh9292 : can you help? Maybe we need to update the documentation?

**Comment by NeumeisterGit** [comment]
I found the problem: Blueprints don't have the "double" data type... My problem is, that I receive 8-Byte data types (LReal) and I can't just cut them into floats... And there is no way to have a "float64", but there is a "int64" but well, it dosen't work with a mantisse...

Need it for a science project for a university

--> Ahh and I tried to "label" this topic, but afterwards it dosen't work anymore ^^

**Comment by extall** [comment]
Ok, yeah, this then is not an issue of the plugin which is why I will close this issue. If you feel that something is missing in documentation, please create a separate ticket.

FYI, as an aside, I've been playing with double-to-single precision conversion previously in UE4 with Blueprints and C++. The approach was to leave critical computations to C++ and expose the results to the CG environment via Blueprints. Sure, some loss of precision will occur (double to single), but it is not critical for visualization purposes.

**Comment by NeumeisterGit** [comment]
I found out following... In Unreal Engine 5 it seems that float is already "double precision" (and 8-Byte...) This is so embarassing xD

![image](https://user-images.githubusercontent.com/72918486/203317969-c8f6080e-31df-421a-bf10-566b66ced46a.png)
