### ISSUE TITLE
Plugin does not work with UE 5.0.3

### ISSUE THREAD

**Issue by SirRahulKulkarni** [is-centre/udp-ue4-plugin-win64#15]
![UDPCommunication_UE503_Error](https://github.com/is-centre/udp-ue4-plugin-win64/assets/15083690/dd3cf461-9112-4ba2-af60-b1db8df6cd98)

Dears,

I keep on getting the above error when I am trying to use the Plugin for UE 5.0.3. I tried using the Plugins for 5.00 and 5.0 (in the folders on GitHub) and still getting the same error. It works find with UE 4.26 version though. I would really appreciate if you can help me with the above issue.

Thank you for your kind support.

**Comment by extall** [comment]
Interesting, we didn't have any issues with minor versions before as far as I can remember, so this might need to be investigated.

**Comment by SirRahulKulkarni** [comment]
Dear Aleksei,

Thank you for the quick revert. I am installing UE 5.1 and am sure it should run smoothly on that!

**Comment by extall** [comment]
Yes, 5.00 didn't work with 5.0.3 for some reason.

Well, in any case, the 5.0.3 version has been released as well: https://github.com/is-centre/udp-ue4-plugin-win64/tree/master/5.03/UDPCommunication

I did not add it to "Releases" but it's in the repository, and if the repository is cloned, you can just grab it from the corresponding folder.

Closing issue.
