### ISSUE TITLE
A demo video showing how to use UDP Receiver

### ISSUE THREAD

**Issue by SirRahulKulkarni** [is-centre/udp-ue4-plugin-win64#17]
Dears,

Could you kindly make a demo video showing how to use UDP Receiver, (similar to the one you have for UDP Sender on YT). I have tried to use the UDP receiver but not sure how Blueprint nodes should be connected.
Much appreciated. Thank you.

**Comment by SirRahulKulkarni** [comment]
I was able to get UDP Receiver working as I followed the Crane3D example project. So closing this issue.

**Comment by extall** [comment]
God job!

You are right that there is a lack of fully fledged documentation. I will create an issue for that.
