### ISSUE TITLE
Can this plugin be used on iOS

### ISSUE THREAD

**Issue by chouchouxia** [is-centre/udp-ue4-plugin-win64#2]
Hello , I am trying to make a function that makes Ipad control PC. I want to use this plugins ,but I am not sure can this plugin be used on iOS.

**Comment by extall** [comment]
The C++ code of the plugin does not depend on any windows-specific libraries or functions. So, in theory, yes, it should be possible to compile and use the plugin on iOS. However, we do not have the ability to test it as we are not targeting iOS at the moment.

**Comment by chouchouxia** [comment]
Thank you very much. I'll try it tomorrow.




------------------ 原始邮件 ------------------
发件人: "Aleksei Tepljakov"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 晚上11:04
收件人: "is-centre/udp-ue4-plugin-win64"<udp-ue4-plugin-win64@noreply.github.com>;
抄送: "黄敏明"<1804235271@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [is-centre/udp-ue4-plugin-win64] Can this plugin be used on iOS(#2)




The C++ code of the plugin does not depend on any windows-specific libraries or functions. So, in theory, yes, it should be possible to compile and use the plugin on iOS. However, we do not have the ability to test it as we are not targeting iOS at the moment.

**Comment by chouchouxia** [comment]
Hey , I had tried in iPad, when I open the app in iPad, it broke down right now. But the project worked correctly in two windows computers' communications.
And I found that the following codes led to the problem:
`	SenderSocket->SetSendBufferSize(SendSize, SendSize);
	SenderSocket->SetReceiveBufferSize(SendSize, SendSize);`

the app in iPad can start correctly when I delete above codes.

<--    -->

I found that UE4 UdpMessaging Plugin also use the same method:
`	Socket->SetReceiveBufferSize(2*1024*1024, NewSize);
	Socket->SetSendBufferSize(2*1024*1024, NewSize);`

I am confused about what led to the problem. I would greatly appreciate if you could give me some suggustions...

**Comment by chouchouxia** [comment]
`	SenderSocket = FUdpSocketBuilder(*SocketName)
		.AsReusable()
		.WithBroadcast();`

UdpSocketBuilder created failed in iPad. So SenderSocket is NULL.
What should I do to make it create successful in iPad........Great appreciation~

**Comment by chouchouxia** [comment]
UdpSocketBuilder created successfully in windows computers , and woks well.

**Comment by extall** [comment]
I don't think it's an issue of the plugin itself. Most likely this has to do with security settings on the iPad. Or, the Network module of UE is for some reason not supported there.

**Comment by chouchouxia** [comment]
Just as you say , although I don't have found the reason , I found a method to avoid this problem. I am a  newcomer ， hope I can really solve it one day.
this is my method in UE4 Answer Hub: https://answers.unrealengine.com/questions/894831/view.html
Thank you very much. This plugin helps me a lot~~~蟹蟹
