### ISSUE TITLE
I want to receive a string in Json format as a String using UDPReciver.

### ISSUE THREAD

**Issue by ki-kadu** [is-centre/udp-ue4-plugin-win64#22]
We apologize that some sentences are difficult to read due to machine translation.

I am trying to use a UE5.1 blueprint project.
I want to receive JSON format data sent from Python via UDP as a single String, but I cannot receive it due to a bad modification method.
Disassemble UDPData" outputs it as a String, but when I try to print it, nothing is output.

In the initial state of float and int, I was able to confirm that there is a number in the float, so it does not seem that the data is not being sent.

Could you please advise me on how to fix the source and what steps I should take after the fix.

UDPData.h
#pragma once

#include "Serialization/Archive.h"
#include "UDPData.generated.h"

USTRUCT(BlueprintType)
struct FUDPData {
	GENERATED_USTRUCT_BODY()
	UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		FString fstring1 = "";
	FUDPData() {
	}
};

FORCEINLINE FArchive& operator<<(FArchive &Ar, FUDPData &Structure)
{
	Ar << Structure.fstring1;
	return Ar;
}

**Comment by saleh9292** [comment]
Hello, after updating the plugin code, make sure you recompile your project.

Then, you can use Blueprints to initialize your receiver and access the string data. An example is shown in the figure below:

![image](https://github.com/is-centre/udp-ue4-plugin-win64/assets/22989635/a2cbace1-ef7e-49df-92a7-cbd79366fc74)


Once you have the string, you will need to parse the JSON.

**Comment by ki-kadu** [comment]
Excuse me from the machine translation.

I'm sorry, I just started using UE and I'm inexperienced,
I don't know how to recompile a project.

In a text editor, edit the UDPData.h and then
I have tried various steps, such as updating the visual studio project from the Unreal Engine C++ project, starting visual studio and rebuilding, but the modifications are not reflected.

**Comment by extall** [comment]
It is not the scope of this project to teach basics of Unreal Engine's C++ pipeline.

Perhaps, eventually we will have a plugin configurator of some sort that you can just use without any coding knowledge. But at the moment, for anything more advanced, like chaning the data structures and so on, you will have to recompile the binaries.

At the very minimum, you will need to install a suitable version of Visual Studio (check which one you need for the specific version of Unreal Engine) and the components recommended for Unreal Engine development. If you are a beginner in this, many things will likely go wrong, but it's a learning process.

For the time being, I am closing this issue.
