### ISSUE TITLE
Please add sending/receiving "STRING" to the plugin

### ISSUE THREAD

**Issue by MSTIGM** [is-centre/udp-ue4-plugin-win64#5]
Hi,
Thank you so much for your great plugin...
Could you please add the possibility of sending/receiving "String" to your plugin for UE v4.26?
Your plugin is really awesome and very easy to use/understand comparing to other complex plugins such as SocketIO!
If you could add "String" to your plugin, it could be REALLY useful and great...
Thank you so much for your attentions.
With Kind Regards,
Stig

**Comment by extall** [comment]
@MSTIGM Sorry for the delay in response! I am now on holidays. 

Were you able to find a solution? I think one of my engineers came up with something, but in a forked version. If you still need this, I will talk to him ASAP.

**Comment by MSTIGM** [comment]
Hi @extall ,
Thank you so much for your reply :-) ...
Unfortunately, I couldn't find any solution except using other confusing plugins :-/ ... 
So, I will be very grateful if you could help me :-) ...
As I mentioned before, your plugin is very easy to use compared to other plugins and it could be AMAZING if we can send/receive "STRING" using this plugin :-) ...
I'm looking forward for the link of that forked version :-) ...
Thank you again for your attention.
Take Care and Have Happy Holidays ;-) :-) ...
With Kind Regards,
Stig

**Comment by saleh9292** [comment]
@MSTIGM I just updated the readme with information on how to change the data structure.
I have also included an example of using strings, please try it out and let me know if it is working.

**Comment by extall** [comment]
I assume everything went well and we can close this issue.
