### ISSUE TITLE
Sending/Receiving Input Data

### ISSUE THREAD

**Issue by ghost** [is-centre/udp-ue4-plugin-win64#6]
Thank you so much for this plugin!!
I'm having some trouble sending InputAxis data
In the UDPReceiver 'Is New Data Ready' is returning true, as is UDPSend Array' in UDPSender, however nothing is being output when we print the data from 'Get Data' in UDPReceiver. We are having the same issue with input keys in general.
Any help you can provide is appreciated! :)

**Comment by extall** [comment]
Hello! I see you have closed this issue. For the benefit of the community, can you tell me what the problem was that you were able to fix?

**Comment by extall** [comment]
Looks like it this is not  happening, so I am closing this.
