### ISSUE TITLE
Sending data from python

### ISSUE THREAD

**Issue by helihallow** [is-centre/udp-ue4-plugin-win64#7]
Hi,
Thanks for the plugin, it works well in ue4!
I have a questions about communicating with python. What is the input data format? How to send the array data from python to ue4 plugin?
Thank you!

**Comment by extall** [comment]
OK, so we are discussing the presentation layer of the OSI model. That means it does not matter whether we use Python or C# or whatever, the data structure is always the same in that the communication is done through UDP sockets. The datagrams contain data with the structure as discussed in the current iteration of the readme file. That structure is used to both {serialize the data to} and {de-serialize the data from} the actual datagram payload.

In Python specifically, you could do something like 
```python
from struct import pack, unpack
the_format = "<ffffffffffffffffffffcccsss"
# ...Reading data from socket...
unpacked_data_tuple = unpack(the_format, data)
# Do something with the unpacked data ...
```
(I have not tested the code above, so I am not sure the `char[]` specified by `s` will work as I think it would.)

For sending, you obviously use `pack` instead, keeping the format.

**Comment by helihallow** [comment]
Thank you very much!! It works!! You just saved my life :)

**Comment by extall** [comment]
You are welcome :)
