### ISSUE TITLE
Will there be updates for 4.27 and 5.0?

### ISSUE THREAD

**Issue by b-state** [is-centre/udp-ue4-plugin-win64#8]
Hey, thank you very much for providing this plugin! 

I managed to use the 4.26 version for 4.27 and 5.0 beta by selecting "Switch Unreal Engine version" in my project with the automatic recompiling. 
But will there be official releases for the newer versions?

**Comment by extall** [comment]
Yes. I'm just waiting to clean up the mess in the repository first, and to set up a proper releases page :)
But in the meantime I can look at the situation with the latest UE4/5 and release the plugins for them.

**Comment by b-state** [comment]
Alright, thank you!

**Comment by extall** [comment]
Released. Also available as separate downloads in GitHub releases for the plugin.
5.00 is in early access at the moment, so there may be stability problems and the codebase may change as well requiring to change some code in the plugin.
