### ISSUE TITLE
Will packets be lost if they come in too fast?

### ISSUE THREAD

**Issue by MiloMindbender** [is-centre/udp-ue4-plugin-win64#9]
Hi, sorry to bug you with this.  I'm looking at the code for udpreceiver and am a little confused.  Are the received packets getting buffered somewhere?  Unless I am missing something it appears they are not.

If say, 10 UDP packets come in since my last read, it looks like I would only get the most recently received one, or am I missing something?  Not that familiar with the UE networking and class libraries yet and trying to learn.

**Comment by extall** [comment]
The 10 UDP packets will always arrive in sequence. Assuming the transmission channel is reliable, none should be lost.
Buffer size is set on initialization in the code. If you want to change it, you would have to modify the code and rebuild the plugin.
Perhaps it makes sense to expose this setting to blueprints. Feel free to issue a feature request.

**Comment by MiloMindbender** [comment]
Sorry if I'm being an idiot, but reading the code it looks like the Recv delegate gets called whenever a packet is available, this passes data to archive which converts it to your data format, passes it to updatereceiverobject that stores the data in MyData till someone calls getdata to get it.

It seems like, if another packet comes in before getdata is called, this process will repeat and MyData will be overwritten with the new packet, losing the old one.  

Is there something I'm missing that is preventing MyData from being overwritten every time a new packet arrives?

**Comment by extall** [comment]
No, in fact, it is important to ask such questions. Also, sorry for not replying sooner, I've been on my summer break.

Generally, I think the situation is such that yes, it may happen that packets get lost. But remember, this is UDP — there is NO GUARANTEE that the packet will arrive anyway. Hence, from this perspective it is not really an issue of the plugin, rather of the specification.

Still, thank you for your interest! If you have further questions, feel free to reach out.

**Comment by extall** [comment]
I can also add that in our current application for visualizing control plant dynamics where transmission rates vary from 10Hz to 1kHz, we have not experienced any real issues with the plugin (even if a packet gets lost, it is not critical from the application's point of view, and the user will usually not notice this).

However, if you want to create a reliable multiplayer experience using this plugin, you should probably use something else, like Unreal's server implementation or certain components thereof.
